version: '3.8'

services:
  # Existing Twinning Infrastructure
  nextcloud:
    image: nextcloud:latest
    container_name: twinning-nextcloud
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - nextcloud_data:/var/www/html
      - ./data/nextcloud:/var/www/html/data
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin123
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost
    networks:
      - twinning-network

  prometheus:
    image: prom/prometheus:latest
    container_name: twinning-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - twinning-network

  grafana:
    image: grafana/grafana:latest
    container_name: twinning-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    networks:
      - twinning-network

  firefly:
    image: fireflyiii/core:latest
    container_name: twinning-firefly
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - firefly_upload:/var/www/html/storage/upload
    environment:
      - APP_KEY=base64:SomeRandomStringOf32CharsExactly
      - DB_CONNECTION=sqlite
      - APP_URL=http://localhost:8081
    networks:
      - twinning-network

  influxdb:
    image: influxdb:2.0
    container_name: twinning-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=twinning
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
    networks:
      - twinning-network

  # New: Service Integration Architecture
  twinning-core:
    build: ./twinning-core
    container_name: twinning-orchestrator
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - SOCIAL_SERVICE_URL=http://social-automation:8080
      - PIPELINE_SERVICE_URL=http://pipeline-intelligence:8081
      - GRAFANA_URL=http://grafana:3000
      - NEXTCLOUD_URL=http://nextcloud:80
      - INFLUXDB_URL=http://influxdb:8086
    networks:
      - twinning-network
    depends_on:
      - social-automation
      - pipeline-intelligence
      - influxdb

  social-automation:
    build: 
      context: ./services/social
      dockerfile: Dockerfile
    container_name: twinning-social
    restart: unless-stopped
    environment:
      - TWINNING_API_URL=http://twinning-core:3000
      - NODE_ENV=production
    networks:
      - twinning-network
      
  pipeline-intelligence:
    build:
      context: ./services/pipeline  
      dockerfile: Dockerfile
    container_name: twinning-pipeline
    restart: unless-stopped
    environment:
      - TWINNING_API_URL=http://twinning-core:3000
      - NODE_ENV=production
    networks:
      - twinning-network

  mysql:
    image: mysql:8.0
    container_name: twinning-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=twinning
      - MYSQL_USER=twinning
      - MYSQL_PASSWORD=twinning_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - twinning-network

volumes:
  nextcloud_data:
  prometheus_data:
  grafana_data:
  firefly_upload:
  influxdb_data:
  mysql_data:

networks:
  twinning-network:
    driver: bridge
