name: CI - Keep It Simple

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    name: Basic Quality Checks
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check for broken links in markdown
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        config-file: '.github/workflows/markdown-link-config.json'
        
    - name: Lint markdown files
      uses: DavidAnson/markdownlint-cli2-action@v16
      with:
        globs: '**/*.md'
        config: '.markdownlint.json'
        
    - name: Check that setup script is executable
      run: |
        if [ ! -x "setup-prole-project.sh" ]; then
          echo "❌ Setup script is not executable"
          exit 1
        fi
        echo "✅ Setup script is executable"
        
    - name: Validate issue templates
      run: |
        echo "🔍 Checking issue templates..."
        if [ ! -f ".github/ISSUE_TEMPLATE/bug_report.yml" ]; then
          echo "❌ Bug report template missing"
          exit 1
        fi
        if [ ! -f ".github/ISSUE_TEMPLATE/feature_request.yml" ]; then
          echo "❌ Feature request template missing"  
          exit 1
        fi
        echo "✅ Issue templates look good"
        
    - name: Check for placeholder cleanup
      run: |
        echo "🔍 Looking for uncleaned placeholders..."
        if grep -r "{{.*}}" --exclude-dir=.git --exclude="*TEMPLATE*" --exclude="TEMPLATE-README.md" .; then
          echo "❌ Found uncleaned template placeholders"
          echo "Run the setup script to customize your project"
          exit 1
        fi
        echo "✅ No stray placeholders found"